# Generated by Django 3.1.6 on 2021-03-04 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_braintree_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='braintree_response_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='braintree_response_text',
            field=models.TextField(blank=True),
        ),
    ]
